global:

route:
  group_by: ["..."]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1m
  receiver: "email"

receivers:

  - name: "email"
    email_configs:
      - to: "example@example.com"
        from: "alert@prometheus.com"
        smarthost: sandbox.smtp.mailtrap.io:587
        auth_username: <username_mail>
        auth_password: <password_mail>
        auth_identity: <username_mail>
        send_resolved: true


inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match: 
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
